[package]
name = "ryanlua/satchel"
description = "A modern open-source alternative to Roblox's default backpack."
version = "1.3.2"
license = "MPL-2.0"
authors = ["Ryan Luu <ryan.luu@ryanluu.dev>"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]
topbarplus = "1foreverhd/topbarplus@3.2.5"
