[package]
name = "ryanlua/satchel"
description = "A modern open-source alternative to Roblox's default backpack."
version = "1.3.1"
license = "MPL-2.0"
authors = ["Ryan Luu <ryan.luu@ryanluu.dev>"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]
topbarplus = "legitatx/topbarplus@3.0.5"

[dev-dependencies]
testez = "roblox/testez@0.4.1"
