[package]
name = "ryanlua/satchel"
description = "A modern open-source alternative to Roblox's default backpack."
version = "1.4.1"
license = "MPL-2.0"
authors = ["Ryan Luu <ryan.luu@ryanluu.dev>"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
homepage = "http://satchel.luau.page/"
repository = "https://github.com/ryanlua/satchel"
exclude = ["**"]
include = ["src", "src/**", "wally.toml", "wally.lock", "default.project.json", "LICENSE", "README.md"]

[dependencies]
topbarplus = "1foreverhd/topbarplus@3.4.0"
