[package]
name = "canary-development/uishelf"
version = "1.1.3"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
exclude = ["**"]
include = [
    "default.project.json",
    "src",
    "src/**",
    "LICENSE",
    "wally.toml",
    "README.md"
]

[dependencies]
Signal = "red-blox/signal@^1.0.0"