name: CI

on:
  pull_request:
    paths:
      - ".github/workflows/ci.yml"
      - "**.luau"
  push:
    paths:
      - ".github/workflows/ci.yml"
      - "**.luau"

permissions:
  contents: read

env:
  OUTPUT_NAME: Satchel
  BUILD_PROJECT: package.project.json

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Rokit
        uses: CompeyDev/setup-rokit@v0.1.2

      - name: Setup Wally
        run: |
          wally install
          rojo sourcemap develop.project.json --output sourcemap.json
          wally-package-types --sourcemap sourcemap.json Packages/

      - name: Run StyLua
        run: stylua --check src/ models/

      - name: Run selene
        run: selene src/ models/

      - name: Build using Rojo
        run: |
          mkdir builds
          rojo build --output builds/$OUTPUT_NAME.rbxm $BUILD_PROJECT
          rojo build --output builds/$OUTPUT_NAME.rbxmx $BUILD_PROJECT

      - name: Archive build files
        uses: actions/upload-artifact@v6
        with:
          name: ${{ env.OUTPUT_NAME }}
          path: builds/
          if-no-files-found: error